name: dist-af
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.1.74
  - libgcc-ng=9.3.0
  - python=3.9.6
  - pytorch=1.9.0
  - pyyaml=5.4.1
  - readline=8.1
  - requests=2.26.0
  - setuptools=52.0.0
  - tqdm=4.62.2
  - typing-extensions=3.10.0.0
  - pip:
      - absl-py==1.4.0
      - biopython==1.79
      - dm-tree==0.1.6
      - et-xmlfile==1.1.0
      - h5py==3.8.0
      - jax==0.4.8
      - jaxlib==0.4.7
      - ml-collections==0.1.0
      - numpy==1.23.5
      - pandas==1.3.2
      - pip==23.0.1
      - scipy==1.11.1
      - tensorboard==2.12.1
      - tensorflow==2.12.0